export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_SORT_SUCCESS = 'LOAD_SORT_SUCCESS';
export const UPDATE_SORT_OPTION = 'UPDATE_SORT_OPTION';
export const SORT_COURSE = 'SORT_COURSE';